import { useEffect, useRef, useState } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import axios from "axios";
import Toast from "../components/Toast";
import ConfirmModal from "../components/ConfirmModal";
import Pagination from "../components/Pagination";
import usePagination from "../hooks/usePagination";
import { esRegistroEnUso, obtenerMensajeError } from "../utils/errorMessages";
import { formatearFecha } from "../utils/dateFormat";
import "../styles/Ordenes.css";

const API_URL="/api", TALLES=Array.from({length:13},(_,i)=>String(i+35));
const tallesVacios=()=>Object.fromEntries(TALLES.map(t=>[t,""]));
export default function Ordenes(){
 const navigate=useNavigate(),[params]=useSearchParams();
 const [ordenes,setOrdenes]=useState([]),[productos,setProductos]=useState([]),[planillas,setPlanillas]=useState([]),[lotes,setLotes]=useState([]),[form,setForm]=useState({producto_id_producto:"",numero_orden:"",fecha:""}),[talles,setTalles]=useState(tallesVacios),[operarios,setOperarios]=useState({corte:"",aparado:""}),[materiales,setMateriales]=useState([""]),[materialBusquedas,setMaterialBusquedas]=useState([""]),[mostrar,setMostrar]=useState(false),[idEditando,setIdEditando]=useState(null),[toast,setToast]=useState(null),[confirmacion,setConfirmacion]=useState(null),[busqueda,setBusqueda]=useState(""),[cargando,setCargando]=useState(true);const formRef=useRef(null);
 const cargar=async()=>{try{const[o,p,pl,l]=await Promise.all([axios.get(`${API_URL}/ordenes/`),axios.get(`${API_URL}/productos/`),axios.get(`${API_URL}/planillas/`),axios.get(`${API_URL}/lotes/`)]);setOrdenes(o.data);setProductos(p.data);setPlanillas(pl.data);setLotes(l.data);}catch(e){console.error(e);setToast({type:"error",title:"No se pudo cargar",message:"Revisá la conexión con el servidor."});}finally{setCargando(false);}};
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{cargar();},[]);
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{const p=params.get("producto"),b=sessionStorage.getItem("borrador-nueva-orden");if(p&&b){const x=JSON.parse(b);setForm({...x.form,producto_id_producto:p==="cancelado"?x.form.producto_id_producto:p});setTalles(x.talles);setOperarios(x.operarios);setMateriales(x.materiales);setMaterialBusquedas(x.materialBusquedas||[""]);setMostrar(true);sessionStorage.removeItem("borrador-nueva-orden");navigate("/ordenes",{replace:true});}},[params,navigate]);
 const total=Object.values(talles).reduce((s,x)=>s+Number(x||0),0);
 const etiquetaLote=lote=>`${lote.material||"Material"}${lote.color?` (${lote.color})`:""} · Remito ${lote.numero_remito||"-"}`;
 const actualizarMaterial=(indice,valor)=>{const busquedas=[...materialBusquedas],ids=[...materiales];busquedas[indice]=valor;const lote=lotes.find(item=>etiquetaLote(item).toLowerCase()===valor.trim().toLowerCase());ids[indice]=lote?String(lote.id_lote||lote.id_lote_materiales):"";if(lote&&indice===ids.length-1){ids.push("");busquedas.push("");}setMateriales(ids);setMaterialBusquedas(busquedas);};
 const reset=()=>{setForm({producto_id_producto:"",numero_orden:"",fecha:""});setTalles(tallesVacios());setOperarios({corte:"",aparado:""});setMateriales([""]);setMaterialBusquedas([""]);setIdEditando(null);};
 const editar=async(o)=>{setForm({producto_id_producto:o.producto_id_producto,numero_orden:o.numero_orden,fecha:o.fecha});setIdEditando(o.id_orden);setMostrar(true);try{const[d,u]=await Promise.all([axios.get(`${API_URL}/ordenes/${o.id_orden}/talles`),axios.get(`${API_URL}/uso-materiales/`)]);const tv=tallesVacios();d.data.forEach(x=>tv[x.talle]=x.cantidad_pares);setTalles(tv);const r=planillas.find(x=>Number(x.orden_fabricacion_id_orden)===Number(o.id_orden)&&x.numero_planilla?.toUpperCase()==="R013");if(r){const op=await axios.get(`${API_URL}/planillas/${r.id_planilla}/operarios`);setOperarios({corte:op.data.find(x=>x.etapa?.toLowerCase()==="corte")?.nombre_operario||"",aparado:op.data.find(x=>x.etapa?.toLowerCase()==="aparado")?.nombre_operario||""});const ids=[...new Set(u.data.filter(x=>Number(x.planilla_produccion_id_planilla)===Number(r.id_planilla)).map(x=>String(x.lote_materiales_id_lote||x.id_lote)))];setMateriales(ids.length?[...ids,""]:[""]);setMaterialBusquedas(ids.length?[...ids.map(id=>etiquetaLote(lotes.find(x=>String(x.id_lote||x.id_lote_materiales)===id)||{})),""]:[""]);}}catch(e){setToast({type:"error",title:"No se pudo editar",message:obtenerMensajeError(e,"orden")});}};
 const guardar=async e=>{e.preventDefault();const datos={...form,producto_id_producto:Number(form.producto_id_producto),talles:TALLES.map(t=>({talle:t,cantidad_pares:Number(talles[t]||0)})).filter(x=>x.cantidad_pares>0),operario_corte:operarios.corte,operario_aparado:operarios.aparado,materiales:[...new Set(materiales.filter(Boolean).map(Number))]};try{if(idEditando)await axios.put(`${API_URL}/ordenes/${idEditando}`,datos);else await axios.post(`${API_URL}/ordenes/`,datos);setToast({type:"success",title:"Orden guardada",message:`Objetivo general: ${total} pares. Las variantes se asignan en Planillas.`});setMostrar(false);reset();cargar();}catch(error){setToast({type:"error",title:"No se pudo guardar",message:obtenerMensajeError(error,"orden")});}};
 const eliminar=id=>setConfirmacion({title:"Eliminar orden",message:"Se eliminará la orden seleccionada.",confirmText:"Eliminar",danger:true,onConfirm:async()=>{setConfirmacion(null);try{await axios.delete(`${API_URL}/ordenes/${id}`);setOrdenes(actuales=>actuales.filter(orden=>orden.id_orden!==id));setToast({type:"success",title:"Orden eliminada",message:"La orden se eliminó correctamente."});}catch(error){if(esRegistroEnUso(error)){setConfirmacion({title:"Orden con trazabilidad asociada",message:"Esta orden tiene planillas, producción, materiales u otros registros vinculados. Si continuás, se eliminará todo su recorrido y se perderá la trazabilidad relacionada.",confirmText:"Eliminar de todos modos",danger:true,onConfirm:async()=>{setConfirmacion(null);try{await axios.delete(`${API_URL}/ordenes/${id}?forzar=1`);setOrdenes(actuales=>actuales.filter(orden=>orden.id_orden!==id));setToast({type:"success",title:"Orden eliminada",message:"También se eliminaron sus planillas y registros de trazabilidad."});}catch(errorForzado){setToast({type:"error",title:"No se pudo eliminar",message:obtenerMensajeError(errorForzado,"orden")});cargar();}}});}else{setToast({type:"error",title:"No se pudo eliminar",message:obtenerMensajeError(error,"orden")});}}}});
 const filtradas=ordenes.filter(o=>`${o.numero_orden} ${o.producto} ${o.color}`.toLowerCase().includes(busqueda.toLowerCase())),paginacion=usePagination(filtradas);
 return <section className="ordenes">{toast&&<Toast {...toast} onClose={()=>setToast(null)}/>}<ConfirmModal open={Boolean(confirmacion)} {...confirmacion} onCancel={()=>setConfirmacion(null)} onConfirm={confirmacion?.onConfirm}/><div className="ui-page-header ui-page-header-row"><div><h1>Órdenes de Fabricación</h1><p>Producto, color fijo y cantidad objetivo. Las variantes se asignan en Planillas.</p></div><button className="ui-btn ui-btn-primary" onClick={()=>{reset();setMostrar(true);}}>+ Nueva orden</button></div>
 {mostrar&&<div className="ui-form-card" ref={formRef}><h2>{idEditando?"Editar orden":"Nueva orden · Objetivo general"}</h2><form className="form-orden" onSubmit={guardar}><div className="orden-datos-grid"><label>Producto base<div className="orden-producto-selector"><select required value={form.producto_id_producto} onChange={e=>setForm({...form,producto_id_producto:e.target.value})}><option value="">Seleccione producto</option>{productos.map(p=><option key={p.id_producto} value={p.id_producto}>{p.nombre_producto} ({p.color})</option>)}</select><button type="button" className="orden-alta-producto" onClick={()=>{sessionStorage.setItem("borrador-nueva-orden",JSON.stringify({form,talles,operarios,materiales,materialBusquedas}));navigate("/productos?nuevo=1&volver=ordenes");}}>+</button></div></label><label>Número de orden<input required value={form.numero_orden} onChange={e=>setForm({...form,numero_orden:e.target.value})}/></label><label>Fecha<input type="date" required value={form.fecha} onChange={e=>setForm({...form,fecha:e.target.value})}/></label></div><div className="talles-orden-header"><div><h3>Cantidad objetivo por talle</h3><p>La distribución de la orden; después cada planilla indica qué variante fabrica.</p></div><strong className="total-orden">Total: {total} pares</strong></div><div className="talles-orden-grid">{TALLES.map(t=><label key={t} className={Number(talles[t])?"talle-con-cantidad":""}><span>Talle {t}</span><input type="number" min="0" value={talles[t]} placeholder="0" onChange={e=>setTalles({...talles,[t]:e.target.value})}/></label>)}</div><div className="orden-r013-grid"><label>Operario para corte<input required value={operarios.corte} onChange={e=>setOperarios({...operarios,corte:e.target.value})}/></label><label>Taller de aparado (opcional)<input value={operarios.aparado} onChange={e=>setOperarios({...operarios,aparado:e.target.value})}/></label></div><div className="orden-materiales"><h3>Material utilizado</h3>{materiales.map((id,i)=><div className="orden-material-fila" key={i}><input type="search" list="materiales-recibidos-orden" value={materialBusquedas[i]||""} onChange={e=>actualizarMaterial(i,e.target.value)} placeholder="Buscar por material, color o remito" pattern={id?undefined:"(?!)"}/></div>)}</div><datalist id="materiales-recibidos-orden">{lotes.map(x=><option key={x.id_lote||x.id_lote_materiales} value={etiquetaLote(x)}/>)}</datalist><div className="ui-form-actions"><button className="ui-btn ui-btn-primary">Guardar</button><button type="button" className="ui-btn ui-btn-secondary" onClick={()=>setMostrar(false)}>Cancelar</button></div></form></div>}
 {cargando?<p>Cargando órdenes...</p>:<><div className="ui-search-bar"><input className="ui-input" placeholder="Buscar orden, producto o color..." value={busqueda} onChange={e=>setBusqueda(e.target.value)}/></div><div className="ui-table-card"><table className="ui-data-table"><thead><tr><th>Nº Orden</th><th>Producto base</th><th>Color fijo</th><th>Total</th><th>Fecha</th><th>Acciones</th></tr></thead><tbody>{paginacion.pageItems.map(o=><tr key={o.id_orden}><td>{o.numero_orden}</td><td>{o.producto}</td><td>{o.color||"-"}</td><td>{o.total_pares}</td><td>{formatearFecha(o.fecha)}</td><td><button className="ui-btn ui-btn-secondary" onClick={()=>editar(o)}>Editar</button> <button className="ui-btn ui-btn-danger" onClick={()=>eliminar(o.id_orden)}>Eliminar</button></td></tr>)}</tbody></table></div><Pagination {...paginacion}/></>}
 </section>;
}
